### ISSUE TITLE
creating model Using a compound primary key

### ISSUE THREAD

**Issue by mrwhite1** [dtoubelis/sails-cassandra#38] opened 2016-09-09 10:56 UTC
when i set more than one primary key it gives error of duplicate primary key. i want to achieve functionality like [this link](https://docs.datastax.com/en/cql/3.1/cql/cql_using/use_compound_keys_t.html) . so that i can cluster the data.

**Comment by dtoubelis** [comment] 2016-09-09 15:52
We tried to do this in the past but it turned out ugly (it used CQL statements directly in the model definition breaking any compatibility). The problem is that Waterline has no notion of composite key in the same sense as Cassandra does. For example construct like this:
```sql
PRIMARY KEY ((block_id, breed), color, short_hair)
```
Has no meaning in SQL world but it defines composite partition key with clustering columns in Cassandra.

In order for this t work it has to be supported on abstraction level (i.e. in Waterline). However, given that the Sails/Waterline projects are stagnant it is unlikely to happen in foreseeable future (or ever).

Currently, the only alternative is to create a table with composite key separately and only use `sails-cassandra` to access it and there is not much I can do about it.

**Comment by mrwhite1** [comment] 2016-09-09 17:03
ok thanks for the quick reply.. and yeah i already did it using alternative. just wanted to know if i can specify it in model only.. anyways if this is the case then we shouldn't allow sails to create tables from model just like any other adapters (eg. MySql) ?

**Comment by dtoubelis** [comment] 2016-09-09 17:31
I personally consider creation of tables directly from ORM/ODM a rather dangerous thing and it is only suitable for development. Even with SQL databases, I maintain schema separately with something like `liquibase`. I think you are on the right track creating your tables externally :-) I'm closing this issue for now but feel free to comment ;-)

**Closed by dtoubelis** 2016-09-09 17:31 UTC
