### ISSUE TITLE
Many-Many relationship by-columns error

### ISSUE THREAD

**Issue by zaheershaik** [dtoubelis/sails-cassandra#22] opened 2015-05-13 06:55 UTC
Hello,

I have two entities user and vendor joined with many-many relationship. Details below. After, I create the vendor table with a POST request and GET a vendor, I get "**No indexed columns present in by-columns clause with Equal operator**" error. Could you please check and let me know what am I doing wrong here? It looks like the join table doesn't have indexes created as requested by the parent entities.

**api/models/User.js**
```javascript
module.exports = {

  attributes: {
    id: {type: 'string', primaryKey: true, autoIncrement: true},
    vendors: {collection: 'vendor', via: 'users', **index: true**},
    ownedVendor: {model: 'vendor'},
  }
};
```

**api/models/Vendor.js**
```javascript
module.exports = {

  attributes: {
    id: {type: 'string', primaryKey: true, autoIncrement: true},
    name: {type: 'string', required: true},
    users: {collection: 'user', via: 'vendors', dominant: true, **index: true**},
    owner: {model: 'user'}
  }

};
```

**Create POST Request for Vendor**
```javascript
http://localhost:1337/vendor
{
  "name": "test vendor 1"
}
```

**GET Request**
```javascript
http://localhost:1337/vendor/fe1dccb2-f93b-11e4-974e-d88266ae0fd7
{
  "error": "E_UNKNOWN",
  "status": 500,
  "summary": "Encountered an unexpected error",
  "raw": {
    "name": "ResponseError",
    "message": **"No indexed columns present in by-columns clause with Equal operator"**,
    "info": "Represents an error message from the server",
    "code": 8704,
    "query": **"SELECT id,user_vendors,vendor_users FROM user_vendors__vendor_users WHERE vendor_users IN (?) ALLOW FILTERING;"**
  }
}
```

**Cassandra JOIN Table**
```sql
CREATE TABLE nebula.user_vendors__vendor_users (
  id timeuuid PRIMARY KEY,
  user_vendors text,
  vendor_users text
) WITH
  bloom_filter_fp_chance=0.010000 AND
  caching='KEYS_ONLY' AND
  comment='' AND
  dclocal_read_repair_chance=0.100000 AND
  gc_grace_seconds=864000 AND
  read_repair_chance=0.000000 AND
  replicate_on_write='true' AND
  populate_io_cache_on_flush='false' AND
  compaction={'class': 'SizeTieredCompactionStrategy'} AND
  compression={'sstable_compression': 'LZ4Compressor'};
```

**Comment by zaheershaik** [comment] 2015-05-13 07:04
BTW, I'm using 0.10.9 of the module.

**Comment by dtoubelis** [comment] 2015-05-13 14:13
I think the problem is that with many-to-many association, `sails/waterline` would create joining table automatically. In your case `sails/waterline` creates `user_vendors__vendor_users` table, however it seems it does not create indexes for the joining table. I will look into it.

**Comment by dtoubelis** [comment] 2015-05-13 15:13
Keep in mind that joining tables in this way is alien to Cassandra. The recommended way is to denormalize, otherwise you are not getting full advantage of bigtable data model reducing Cassandra to crippled version of SQL database. Here are some guidelines you may want to consider:

- do not let `sail/waterline`create collections for you. Create them via CQL script and use `sails/waterline` to map existing structures. `sails/waterline`  knows nothing about clustered primary keys and it is unable to create them.
- denormalize data. In your case you could create two tables `users_by_vendor` and `vendors_by_user` with clustered keys. There will be some duplication of data but it is alright according to Cassandra folks.
- choose good partitioning key. This highly depends on type of queries you normally do and what is more important for you - avoiding hot spots or having data sorting capability.
- check cassandra guidelines for using `IN` criteria and if not sure then just avoid it altogether.
- use denormalized tables to retrieve all information in a single query if possible.

**Comment by zaheershaik** [comment] 2015-05-13 16:47
Thanks for the responses. I'll create the joining entities separately and that should alleviate the problem. 

Just to mention, the column families,  JOIN table (user_vendors__vendor_users) and the IN clause query (WHERE vendor_users IN (?)) are all generated by the module/waterline. 

Any plans on creating the indexes automatically while generating the column families? I believe it is imperative to have indexes on the columns in the generated join table, otherwise the many-many relationship from sails wouldn't work.

**Comment by zaheershaik** [comment] 2015-05-13 17:10
I will think in terms of denormalizing the data. It would be good to if the models support the related entities land into different column families. Something like the following User model, which would enter the billing address into a separate column family. 

I understand that this comment might not be related to this module, but was hoping to have sails/your module provide support for this sometime in future.

```javascript
{
  id: 1,
  name: 'John Smith',
  billingAddress: {
    street: '123 Main St',
    city: 'San Jose',
    state: 'CA',
    zipCode: '95124'
  }
}
```
Referred from:  http://docs.strongloop.com/display/public/LB/Embedded+models+and+relations

**Comment by dtoubelis** [comment] 2015-05-13 20:08
It seems that joining model that model that is automatically created by `sails/waterline` does not declare any indexes. That would be not a big deal for SQL database but it does not work well with cassandra. I'll try to address this with upstream, but it may take awhile.

**Comment by zaheershaik** [comment] 2015-05-13 21:33
Sure, thanks for the consideration.

**Comment by dtoubelis** [comment] 2016-09-06 13:51
It looks like sails/waterline projects are slowly dying, so chances of this implemented in the mainstream are very slim. I'm closing this issue for now but feel free to reopen it if you have more info.

**Closed by dtoubelis** 2016-09-06 13:51 UTC
